-- Generated by Pivotal from: football_demo.ipynb
-- SQL export — paste each query into your SQL tool of choice.
-- Python-only operations (plot, apply, etc.) are omitted.


# [Cell 2] pivotal → sql
-- [from database: database.sqlite]
-- match: SELECT * FROM Match
-- league: SELECT * FROM League
-- team: SELECT * FROM Team

# [Cell 4] pivotal → sql
-- [skipped: filter with Python variable reference]
WITH
_cte_0_league_names AS (
  SELECT * FROM league
),
_cte_1_league_names AS (
  SELECT * EXCLUDE (id, name), id AS league_id, name AS league_name FROM _cte_0_league_names
),
_cte_2_league_names AS (
  SELECT league_id, league_name FROM _cte_1_league_names
),
_cte_3_match AS (
  SELECT * FROM match
),
_cte_4_match AS (
  SELECT * FROM _cte_3_match INNER JOIN league_names USING (league_id)
),
_cte_5_match AS (
  SELECT *, LEFT(season, 4) || '-' || RIGHT(season, 2) AS season_clean FROM _cte_4_match
),
_cte_6_match AS (
  SELECT *, home_team_goal + away_team_goal AS total_goals FROM _cte_5_match
)
SELECT * FROM _cte_6_match

# [Cell 5] pivotal → sql
WITH
_cte_0_goal_summary AS (
  SELECT * FROM match
),
_cte_1_goal_summary AS (
  SELECT * EXCLUDE (league_name), league_name AS League FROM _cte_0_goal_summary
),
_cte_2_goal_summary AS (
  SELECT * FROM PIVOT _cte_1_goal_summary ON League USING AVG(total_goals) GROUP BY season_clean
)
SELECT * FROM _cte_2_goal_summary

# [Cell 6] pivotal → sql
WITH
_cte_0_match AS (
  SELECT * FROM match
)
SELECT * FROM _cte_0_match

# [Cell 7] pivotal → sql
WITH
_cte_0_goal_summary AS (
  SELECT * FROM goal_summary
)
SELECT * FROM _cte_0_goal_summary

# [Cell 8] pivotal → sql
WITH
_cte_0_team AS (
  SELECT * FROM team
),
_cte_1_team AS (
  SELECT team_api_id, team_long_name FROM _cte_0_team
)
SELECT * FROM _cte_1_team

# [Cell 9] pivotal → sql
-- [skipped: dropna without explicit column list requires runtime schema]
WITH
_cte_0_win_summary AS (
  SELECT * FROM match
),
_cte_1_win_summary AS (
  SELECT *, CASE WHEN home_team_goal > away_team_goal THEN home_team_api_id WHEN home_team_goal < away_team_goal THEN away_team_api_id ELSE NULL END AS winner_id FROM _cte_0_win_summary
),
_cte_2_win_summary AS (
  SELECT * FROM _cte_1_win_summary NATURAL LEFT JOIN team
),
_cte_3_win_summary AS (
  SELECT *, 1 AS wins FROM _cte_2_win_summary
),
_cte_4_win_summary AS (
  SELECT team_long_name, league_name, SUM(wins) AS wins_sum FROM _cte_3_win_summary GROUP BY team_long_name, league_name
),
_cte_5_win_summary AS (
  SELECT team_long_name AS Team, league_name, wins AS Wins FROM _cte_4_win_summary
),
_cte_6_win_summary AS (
  SELECT * FROM _cte_5_win_summary ORDER BY Wins ASC
),
_cte_7_win_summary AS (
  SELECT * FROM _cte_6_win_summary WHERE Wins > 50
)
SELECT * FROM _cte_7_win_summary

# [Cell 10] pivotal → sql
WITH
_cte_0_win_summary AS (
  SELECT * FROM win_summary
)
SELECT * FROM _cte_0_win_summary

# [Cell 11] pivotal → sql
-- [skipped: dropna without explicit column list requires runtime schema]
WITH
_cte_0_homematch AS (
  SELECT * FROM match
),
_cte_1_homematch AS (
  SELECT *, home_team_goal - away_team_goal AS GD FROM _cte_0_homematch
),
_cte_2_homematch AS (
  SELECT home_team_api_id AS team_id, date, GD FROM _cte_1_homematch
),
_cte_3_homematch AS (
  SELECT * FROM _cte_2_homematch ORDER BY team_id ASC, date ASC
),
_cte_4_home_away_match AS (
  SELECT * FROM match
),
_cte_5_home_away_match AS (
  SELECT *, away_team_goal - home_team_goal AS GD FROM _cte_4_home_away_match
),
_cte_6_home_away_match AS (
  SELECT away_team_api_id AS team_id, date, GD FROM _cte_5_home_away_match
),
_cte_7_home_away_match AS (
  SELECT * FROM _cte_6_home_away_match ORDER BY team_id ASC, date ASC
),
_cte_8_home_away_match AS (
  SELECT * FROM _cte_7_home_away_match UNION ALL SELECT * FROM homematch
),
_cte_9_home_away_match AS (
  SELECT *, LAG(GD, 1) OVER (PARTITION BY team_id ORDER BY date) AS GD_lag FROM _cte_8_home_away_match
),
_cte_10_home_away_match AS (
  SELECT *, AVG(GD_lag) OVER (PARTITION BY team_id ORDER BY date ROWS BETWEEN 3 PRECEDING AND CURRENT ROW) AS pastgame_GD FROM _cte_9_home_away_match
)
SELECT * FROM _cte_10_home_away_match

# [Cell 13] pivotal → sql
WITH
_cte_0_home_away_match AS (
  SELECT * FROM home_away_match
),
_cte_1_fitted AS (
  SELECT * FROM fitted
)
SELECT * FROM _cte_1_fitted

# [Cell 14] pivotal → sql
-- [skipped: no SQL generator for 'save']
