# Generated by Pivotal from: football_demo.ipynb
import pandas as pd


# [Cell 1]
import pivotal
%pivotal_set canvas=a4, viewer_font=0.9, backend=pandas

# [Cell 2]
big4 = ["England Premier League", "Spain LIGA BBVA", "Germany 1. Bundesliga", "Italy Serie A"]

# [Cell 3] pivotal → pandas
import sqlite3 as _sqlite3
with _sqlite3.connect('database.sqlite') as _conn:
    Match = pd.read_sql('SELECT * FROM Match', _conn)
_kw_cols = [c for c in Match.columns if c.lower() in frozenset({'avg', 'all', 'exclude', 'drop', 'rows', 'merge', 'rename', 'filter', 'table', 'agg', 'on', 'endswith', 'false', 'save', 'median', 'where', 'unpivot', 'load', 'left', 'sum', 'rolling', 'and', 'dropna', 'select', 'max', 'or', 'true', 'contains', 'cummax', 'fillna', 'cummean', 'sort', 'from', 'order', 'apply', 'in', 'group', 'min', 'concat', 'include', 'cumsum', 'cummin', 'std', 'pivot', 'none', 'asc', 'between', 'desc', 'outer', 'startswith', 'lead', 'as', 'mean', 'lag', 'plot', 'count', 'cols', 'inner', 'by', 'distinct', 'python', 'rank', 'right', 'not'})]
if _kw_cols:
    import warnings
    warnings.warn(
        f"Table 'Match' has columns that are Pivotal keywords: {_kw_cols}. "
        "Use a 'python' block to reference them.",
        UserWarning, stacklevel=2)
#__pivotal__
__table_name__ = 'Match'
#__pivotal__

import sqlite3 as _sqlite3
with _sqlite3.connect('database.sqlite') as _conn:
    League = pd.read_sql('SELECT * FROM League', _conn)
_kw_cols = [c for c in League.columns if c.lower() in frozenset({'avg', 'all', 'exclude', 'drop', 'rows', 'merge', 'rename', 'filter', 'table', 'agg', 'on', 'endswith', 'false', 'save', 'median', 'where', 'unpivot', 'load', 'left', 'sum', 'rolling', 'and', 'dropna', 'select', 'max', 'or', 'true', 'contains', 'cummax', 'fillna', 'cummean', 'sort', 'from', 'order', 'apply', 'in', 'group', 'min', 'concat', 'include', 'cumsum', 'cummin', 'std', 'pivot', 'none', 'asc', 'between', 'desc', 'outer', 'startswith', 'lead', 'as', 'mean', 'lag', 'plot', 'count', 'cols', 'inner', 'by', 'distinct', 'python', 'rank', 'right', 'not'})]
if _kw_cols:
    import warnings
    warnings.warn(
        f"Table 'League' has columns that are Pivotal keywords: {_kw_cols}. "
        "Use a 'python' block to reference them.",
        UserWarning, stacklevel=2)
#__pivotal__
__table_name__ = 'League'
#__pivotal__

# [Cell 4] pivotal → pandas
if 'League' not in locals() and 'League' not in globals(): raise NameError("name 'League' is not defined")
if not isinstance(League, pd.DataFrame): raise TypeError('League is not a pandas DataFrame')
league_names = League.copy()
#__pivotal__
__table_name__ = 'league_names'
#__pivotal__

league_names = league_names.query('name in @big4')

league_names = league_names.rename(columns={'id': 'league_id', 'name': 'League'})

league_names = league_names.loc[:, ['league_id', 'League']]

if 'Match' not in locals() and 'Match' not in globals(): raise NameError("name 'Match' is not defined")
if not isinstance(Match, pd.DataFrame): raise TypeError('Match is not a pandas DataFrame')
#__pivotal__
__table_name__ = 'Match'
#__pivotal__

Match = Match.merge(league_names, on=['league_id'], how='inner', )

Match['season_clean'] = Match['season'].str[:4] + '-' + Match['season'].str[-2:]

Match['total_goals'] = Match['home_team_goal'] + Match['away_team_goal']

# [Cell 5] pivotal → pandas
if 'Match' not in locals() and 'Match' not in globals(): raise NameError("name 'Match' is not defined")
if not isinstance(Match, pd.DataFrame): raise TypeError('Match is not a pandas DataFrame')
goal_summary = Match.copy()
#__pivotal__
__table_name__ = 'goal_summary'
#__pivotal__

goal_summary = pd.pivot_table(goal_summary, values='total_goals', index='season_clean', columns='League', aggfunc={'total_goals': 'mean'}).reset_index()

import matplotlib.pyplot as plt
_ax = goal_summary.plot(kind='line', x='season_clean', y=big4, xlabel='Season', ylabel='Mean goals')
if '_pivotal_charts' not in globals(): globals()['_pivotal_charts'] = {}
globals()['_pivotal_charts']['goal_chart'] = {'fig': _ax.get_figure(), 'data': goal_summary.copy()}
goal_chart = _ax.get_figure()

# [Cell 6] pivotal → pandas
if 'Match' not in locals() and 'Match' not in globals(): raise NameError("name 'Match' is not defined")
if not isinstance(Match, pd.DataFrame): raise TypeError('Match is not a pandas DataFrame')
#__pivotal__
__table_name__ = 'Match'
#__pivotal__

import matplotlib.pyplot as plt
goal_chart2_df = Match.pivot_table(index='season_clean', columns='League', values='total_goals', aggfunc='mean')
goal_chart2_df.columns = [str(c) for c in goal_chart2_df.columns]
goal_chart2_df = goal_chart2_df.reset_index()
_pivot_y = [c for c in goal_chart2_df.columns if c != 'season_clean']
_ax = goal_chart2_df.plot(x='season_clean', y=_pivot_y, kind='line')
_ax.set_ylabel('Mean goals')
goal_chart2 = _ax.get_figure()
_ax.set_xlabel('Season')
if '_pivotal_charts' not in globals(): globals()['_pivotal_charts'] = {}
globals()['_pivotal_charts']['goal_chart2'] = {'fig': goal_chart2, 'data': goal_chart2_df.copy()}

# [Cell 7] pivotal → pandas
if 'goal_summary' not in locals() and 'goal_summary' not in globals(): raise NameError("name 'goal_summary' is not defined")
if not isinstance(goal_summary, pd.DataFrame): raise TypeError('goal_summary is not a pandas DataFrame')
#__pivotal__
__table_name__ = 'goal_summary'
#__pivotal__

import great_tables as _gt_mod
_gt = _gt_mod.GT(goal_summary, rowname_col='season_clean')
_gt = _gt.tab_header(title='Mean goals scored per game by league and season')
_gt = _gt.tab_stubhead(label='Season')
_gt = _gt.opt_table_font(font='Calibri')
import great_tables.vals as _gt_vals
_gt = _gt.grand_summary_rows(fns={
    'Average': lambda _df: _df.select_dtypes('number').mean()
},
    fmt=lambda x: _gt_vals.fmt_number(x, decimals=2))
import great_tables.style as _gt_style
import great_tables.loc as _gt_loc
_gt = _gt.tab_style(style=_gt_style.text(size='11pt'), locations=[_gt_loc.body(), _gt_loc.stub(), _gt_loc.stubhead(), _gt_loc.column_labels(), _gt_loc.header(), _gt_loc.grand_summary(), _gt_loc.grand_summary_stub()])
_gt = _gt.tab_style(style=_gt_style.text(whitespace='nowrap'), locations=[_gt_loc.stub(), _gt_loc.stubhead(), _gt_loc.grand_summary_stub()])
_gt = _gt.fmt_number(columns=goal_summary.select_dtypes(include='number').columns.tolist(), decimals=2)
import re as _gt_re
def _gt_px_to_pt(h): return _gt_re.sub(r'(\d+(?:\.\d+)?)px', lambda _m: f'{float(_m.group(1)) * 0.75:.4g}pt', h)
_gt_viewer_html = _gt_px_to_pt(_gt.as_raw_html(inline_css=True))
_gt_export_html = _gt_px_to_pt(_gt.as_raw_html(make_page=True, inline_css=True))
_gt_export_html = _gt_export_html.replace('</head>', '<style>p{margin-top:0;margin-bottom:0;}p.MsoNormal,li.MsoNormal,div.MsoNormal{margin:0;}td{mso-line-height-rule:exactly;}td p,th p{margin:0;mso-line-height-rule:exactly;}</style>' + '</head>', 1)
if '_pivotal_gt_tables' not in globals(): globals()['_pivotal_gt_tables'] = {}
globals()['_pivotal_gt_tables']['goal_table'] = {'viewer_html': _gt_viewer_html, 'html': _gt_export_html, 'canvas': 'none'}
from IPython.display import display as _ipyd, HTML as _ipyHTML
_ipyd(_ipyHTML(_gt_viewer_html))

# [Cell 8] pivotal → pandas
import sqlite3 as _sqlite3
with _sqlite3.connect('database.sqlite') as _conn:
    Team = pd.read_sql('SELECT * FROM Team', _conn)
_kw_cols = [c for c in Team.columns if c.lower() in frozenset({'avg', 'all', 'exclude', 'drop', 'rows', 'merge', 'rename', 'filter', 'table', 'agg', 'on', 'endswith', 'false', 'save', 'median', 'where', 'unpivot', 'load', 'left', 'sum', 'rolling', 'and', 'dropna', 'select', 'max', 'or', 'true', 'contains', 'cummax', 'fillna', 'cummean', 'sort', 'from', 'order', 'apply', 'in', 'group', 'min', 'concat', 'include', 'cumsum', 'cummin', 'std', 'pivot', 'none', 'asc', 'between', 'desc', 'outer', 'startswith', 'lead', 'as', 'mean', 'lag', 'plot', 'count', 'cols', 'inner', 'by', 'distinct', 'python', 'rank', 'right', 'not'})]
if _kw_cols:
    import warnings
    warnings.warn(
        f"Table 'Team' has columns that are Pivotal keywords: {_kw_cols}. "
        "Use a 'python' block to reference them.",
        UserWarning, stacklevel=2)
#__pivotal__
__table_name__ = 'Team'
#__pivotal__

# [Cell 9] pivotal → pandas
if 'Match' not in locals() and 'Match' not in globals(): raise NameError("name 'Match' is not defined")
if not isinstance(Match, pd.DataFrame): raise TypeError('Match is not a pandas DataFrame')
win_summary = Match.copy()
#__pivotal__
__table_name__ = 'win_summary'
#__pivotal__

import numpy as np
win_summary['winner_id'] = np.select(
    [win_summary.eval('home_team_goal > away_team_goal'), win_summary.eval('home_team_goal < away_team_goal')],
    [win_summary.eval('home_team_api_id'), win_summary.eval('away_team_api_id')],
    default=None,
)

win_summary = win_summary.merge(Team, how='left', left_on='winner_id', right_on='team_api_id')

win_summary['wins'] = win_summary.eval('1')

win_summary = win_summary.groupby(['team_long_name', 'League']).agg({'wins': 'sum'}).reset_index()

win_summary = win_summary.dropna()

win_summary = win_summary.loc[:, ['team_long_name', 'League', 'wins']].rename(columns={'team_long_name': 'Team', 'wins': 'Wins'})

win_summary = win_summary.sort_values(['Wins'], ascending=[True])

win_summary = win_summary.query('Wins > 50')

# [Cell 10] pivotal → pandas
if 'win_summary' not in locals() and 'win_summary' not in globals(): raise NameError("name 'win_summary' is not defined")
if not isinstance(win_summary, pd.DataFrame): raise TypeError('win_summary is not a pandas DataFrame')
#__pivotal__
__table_name__ = 'win_summary'
#__pivotal__

import matplotlib.pyplot as plt
_by_vals = win_summary['League'].unique()
_n_cols = 2
_n_rows = -(-len(_by_vals) // _n_cols)
_fig, _axes = plt.subplots(_n_rows, _n_cols, figsize=(7 * _n_cols, 5 * _n_rows))
_axes = _axes.flatten() if hasattr(_axes, 'flatten') else [_axes]
for _i, _val in enumerate(_by_vals):
    win_summary[win_summary['League'] == _val].plot(kind='barh', x='Team', y='Wins', legend=False, ylabel='', ax=_axes[_i], title=str(_val))
for _ax in _axes[len(_by_vals):]:
    _ax.set_visible(False)
plt.tight_layout()
if '_pivotal_charts' not in globals(): globals()['_pivotal_charts'] = {}
globals()['_pivotal_charts']['win_plot'] = {'fig': _fig, 'data': win_summary.copy()}
win_plot = _fig

# [Cell 11] pivotal → pandas
if 'Match' not in locals() and 'Match' not in globals(): raise NameError("name 'Match' is not defined")
if not isinstance(Match, pd.DataFrame): raise TypeError('Match is not a pandas DataFrame')
homematch = Match.copy()
#__pivotal__
__table_name__ = 'homematch'
#__pivotal__

homematch['GD'] = homematch.eval('home_team_goal - away_team_goal')

homematch = homematch.loc[:, ['home_team_api_id', 'date', 'GD']].rename(columns={'home_team_api_id': 'team_id'})

homematch = homematch.sort_values(['team_id', 'date'], ascending=[True, True])

if 'Match' not in locals() and 'Match' not in globals(): raise NameError("name 'Match' is not defined")
if not isinstance(Match, pd.DataFrame): raise TypeError('Match is not a pandas DataFrame')
ha_match = Match.copy()
#__pivotal__
__table_name__ = 'ha_match'
#__pivotal__

ha_match['GD'] = ha_match.eval('away_team_goal - home_team_goal')

ha_match = ha_match.loc[:, ['away_team_api_id', 'date', 'GD']].rename(columns={'away_team_api_id': 'team_id'})

ha_match = ha_match.sort_values(['team_id', 'date'], ascending=[True, True])

ha_match = pd.concat([ha_match, homematch], ignore_index=True)

ha_match = ha_match.sort_values('date')
ha_match['pastgame_GD'] = ha_match.groupby(['team_id'])['GD'].transform(lambda x: x.rolling(4).mean())

ha_match = ha_match.dropna()

del homematch

# [Cell 12]
# Switch to Python for some analysis

from statsmodels.nonparametric.smoothers_lowess import lowess

result = lowess(ha_match["GD"], ha_match["pastgame_GD"], frac=0.2)
fitted = pd.DataFrame(result, columns=["pastgame_GD", "Fitted"])
# Polars version
#fitted = pl.from_numpy(result, schema=["pastgame_GD", "Fitted"]) 

pivotal.update()

# [Cell 13] pivotal → pandas
if 'ha_match' not in locals() and 'ha_match' not in globals(): raise NameError("name 'ha_match' is not defined")
if not isinstance(ha_match, pd.DataFrame): raise TypeError('ha_match is not a pandas DataFrame')
#__pivotal__
__table_name__ = 'ha_match'
#__pivotal__

import matplotlib.pyplot as plt
_ax = ha_match.plot(kind='scatter', title='Prior form vs match outcome', x='pastgame_GD', y='GD', xlabel='Past four games mean goal difference', ylabel='Goal difference')
if '_pivotal_charts' not in globals(): globals()['_pivotal_charts'] = {}
globals()['_pivotal_charts']['form_model_chart'] = {'fig': _ax.get_figure(), 'data': ha_match.copy()}
form_model_chart = _ax.get_figure()

if 'fitted' not in locals() and 'fitted' not in globals(): raise NameError("name 'fitted' is not defined")
if not isinstance(fitted, pd.DataFrame): raise TypeError('fitted is not a pandas DataFrame')
#__pivotal__
__table_name__ = 'fitted'
#__pivotal__

import matplotlib.pyplot as plt
if '_pivotal_charts' not in globals() or 'form_model_chart' not in globals()['_pivotal_charts']:
    raise KeyError("plot 'on' target 'form_model_chart' not found - make sure it is created first")
_ax = globals()['_pivotal_charts']['form_model_chart']['fig'].axes[0]
_prev_xlabel = _ax.get_xlabel()
_prev_ylabel = _ax.get_ylabel()
fitted.plot(kind='line', x='pastgame_GD', y='Fitted', c='red', ax=_ax)
_ax.set_xlabel(_prev_xlabel)
_ax.set_ylabel(_prev_ylabel)

# [Cell 14] pivotal → pandas
from pivotal.package import Package as _PivotalPackage
_PivotalPackage.export('football_demo', globals(), fmt='csv', chart_fmt='png')
