# Generated by Pivotal from: football_demo.pivotal (backend: sql)

-- [skipped: python block not supported in SQL CTE mode]
-- [from database: database.sqlite]
-- match: SELECT * FROM Match
-- league: SELECT * FROM League
-- team: SELECT * FROM Team
-- [skipped: python block not supported in SQL CTE mode]
-- [skipped: filter with Python variable reference]
-- [skipped: dropna without explicit column list requires runtime schema]
-- [skipped: dropna without explicit column list requires runtime schema]
-- [skipped: no SQL generator for 'delete']
-- [skipped: python block not supported in SQL CTE mode]
-- [skipped: SQL backend only supports 'save <source> as table <target>']
WITH
_cte_0_league_names AS (
  SELECT * FROM league
),
_cte_1_league_names AS (
  SELECT * EXCLUDE (id, name), id AS league_id, name AS league_name FROM _cte_0_league_names
),
_cte_2_league_names AS (
  SELECT league_id, league_name FROM _cte_1_league_names
),
_cte_3_match AS (
  SELECT * FROM match
),
_cte_4_match AS (
  SELECT * FROM _cte_3_match INNER JOIN league_names USING (league_id)
),
_cte_5_match AS (
  SELECT *, LEFT(season, 4) || '-' || RIGHT(season, 2) AS season_clean FROM _cte_4_match
),
_cte_6_match AS (
  SELECT *, (home_team_goal + away_team_goal) AS total_goals FROM _cte_5_match
),
_cte_7_goal_summary AS (
  SELECT * FROM match
),
_cte_8_goal_summary AS (
  SELECT * EXCLUDE (league_name), league_name AS League FROM _cte_7_goal_summary
),
_cte_9_goal_summary AS (
  SELECT * FROM PIVOT _cte_8_goal_summary ON League USING AVG(total_goals) GROUP BY season_clean
),
_cte_10_match AS (
  SELECT * FROM match
),
_cte_11_goal_summary AS (
  SELECT * FROM goal_summary
),
_cte_12_team AS (
  SELECT * FROM team
),
_cte_13_team AS (
  SELECT team_api_id, team_long_name FROM _cte_12_team
),
_cte_14_win_summary AS (
  SELECT * FROM match
),
_cte_15_win_summary AS (
  SELECT *, CASE WHEN home_team_goal > away_team_goal THEN home_team_api_id WHEN home_team_goal < away_team_goal THEN away_team_api_id ELSE None END AS winner_id FROM _cte_14_win_summary
),
_cte_16_win_summary AS (
  SELECT * FROM _cte_15_win_summary NATURAL LEFT JOIN team
),
_cte_17_win_summary AS (
  SELECT *, 1 AS wins FROM _cte_16_win_summary
),
_cte_18_win_summary AS (
  SELECT team_long_name, league_name, SUM(wins) AS wins_sum FROM _cte_17_win_summary GROUP BY team_long_name, league_name
),
_cte_19_win_summary AS (
  SELECT team_long_name AS Team, league_name, wins AS Wins FROM _cte_18_win_summary
),
_cte_20_win_summary AS (
  SELECT * FROM _cte_19_win_summary ORDER BY Wins ASC
),
_cte_21_win_summary AS (
  SELECT * FROM _cte_20_win_summary WHERE Wins > 50
),
_cte_22_win_summary AS (
  SELECT * FROM win_summary
),
_cte_23_homematch AS (
  SELECT * FROM match
),
_cte_24_homematch AS (
  SELECT *, (home_team_goal - away_team_goal) AS GD FROM _cte_23_homematch
),
_cte_25_homematch AS (
  SELECT home_team_api_id AS team_id, date, GD FROM _cte_24_homematch
),
_cte_26_homematch AS (
  SELECT * FROM _cte_25_homematch ORDER BY team_id ASC, date ASC
),
_cte_27_home_away_match AS (
  SELECT * FROM match
),
_cte_28_home_away_match AS (
  SELECT *, (away_team_goal - home_team_goal) AS GD FROM _cte_27_home_away_match
),
_cte_29_home_away_match AS (
  SELECT away_team_api_id AS team_id, date, GD FROM _cte_28_home_away_match
),
_cte_30_home_away_match AS (
  SELECT * FROM _cte_29_home_away_match ORDER BY team_id ASC, date ASC
),
_cte_31_home_away_match AS (
  SELECT * FROM _cte_30_home_away_match UNION ALL SELECT * FROM homematch
),
_cte_32_home_away_match AS (
  SELECT *, LAG(GD, 1) OVER (PARTITION BY team_id ORDER BY date) AS GD_lag FROM _cte_31_home_away_match
),
_cte_33_home_away_match AS (
  SELECT *, AVG(GD_lag) OVER (PARTITION BY team_id ORDER BY date ROWS BETWEEN 3 PRECEDING AND CURRENT ROW) AS pastgame_GD FROM _cte_32_home_away_match
),
_cte_34_home_away_match AS (
  SELECT * FROM home_away_match
),
_cte_35_fitted AS (
  SELECT * FROM fitted
)
SELECT * FROM _cte_35_fitted
