name: pivotal-demo
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - jupyterlab>=4.0,<5
  - pip
  - pip:
      - "pivotal @ git+https://github.com/nealbob/pivotal-py.git@a114f82543527cc52ef6122cefbb8688f594963c"
      - git+https://github.com/nealbob/pivotal-py.git@a114f82543527cc52ef6122cefbb8688f594963c#subdirectory=editors/jupyterlab
