name: pivotal-demo
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
      - jupyterlab>=4.5.4,<5
      - "pivotal @ git+https://github.com/nealbob/pivotal-py.git@7b6fc4e"
      - git+https://github.com/nealbob/pivotal-py.git@7b6fc4e#subdirectory=editors/jupyterlab
