name: pivotal-demo
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - jupyterlab>=4.0,<5
  - pip
  - pip:
      - git+https://github.com/nealbob/pivotal-py.git@f0c22d5
      - git+https://github.com/nealbob/pivotal-py.git@f0c22d5#subdirectory=editors/jupyterlab
